name: "🏗️ Build Umbraco Packages"
description: ""
author: "James Carter"
branding:
  icon: "refresh-cw"
  color: "gray-dark"
outputs:
  artifact-name:
    description: "Artifact name"
    value: ${{ steps.get-version.outputs.artifact-name }}
  version:
    description: "Version"
    value: ${{ steps.get-version.outputs.package-version }}
inputs:
  project-name:
    description: "Project name"
    required: true
  project-path:
    description: "Project path"
    required: true
  npm-working-dir:
    description: "NPM working directory"
    required: false
  npm-enabled:
    description: "NPM enabled"
    required: false
    default: "false"
  npm-run-command:
    description: "NPM run command"
    required: false
    default: "build"
  node-version:
    description: "Node version"
    required: false
    default: "22.x"
  dotnet-version:
    description: ".NET version"
    required: false
    default: "10.0.x"
  build-output:
    description: "Build output"
    required: false
    default: "./build-output"
  artifact-output:
    description: "Artifact output"
    required: false
    default: "./build-assets"
  dotnet-pack:
    description: "Run dotnet pack"
    required: false
    default: "true"
  strict-umbraco-version:
    description: "Fails the build if the computed Git Major Version does not match this Action's Major version - Used to ensure builds are deterministic for Umbraco releases."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Set env
      id: set-env
      shell: bash
      run: |
        echo "PROJECT_PATH=${{ inputs.project-path }}" >> $GITHUB_ENV
        echo "NPM_WORKING_DIR=${{ inputs.npm-working-dir }}" >> $GITHUB_ENV
        echo "NPM_ENABLED=${{ inputs.npm-enabled }}" >> $GITHUB_ENV
        echo "NPM_RUN_COMMAND=${{ inputs.npm-run-command }}" >> $GITHUB_ENV
        echo "DOTNET_VERSION=${{ inputs.dotnet-version }}" >> $GITHUB_ENV
        echo "BUILD_OUTPUT=${{ inputs.build-output }}" >> $GITHUB_ENV
        echo "ARTIFACT_OUTPUT=${{ inputs.artifact-output }}" >> $GITHUB_ENV
        echo "DOTNET_PACK=${{ inputs.dotnet-pack }}" >> $GITHUB_ENV
        echo "UMBRACO_VERSION=18" >> $GITHUB_ENV

        echo "NODE_VERSION=${{ inputs.node-version }}" >> $GITHUB_ENV
        has_gitversion_config=$(test -f "GitVersion.yml" && echo true || echo false)

        ls -la
        echo "HAS GITVERSION CONFIG: $has_gitversion_config"
        echo "HAS_GITVERSION_CONFIG=$has_gitversion_config" >> $GITHUB_ENV
    - name: Download GitVersion.yml
      shell: bash
      if: ${{ env.HAS_GITVERSION_CONFIG == 'false' }}
      run: curl -sSL https://raw.githubusercontent.com/jcdcdev/jcdcdev.Umbraco.GitHub.Build/refs/tags/v18/config/GitVersion.yml -o GitVersion.yml
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.5.0
      with:
        versionSpec: "6.x"
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v4.5.0
      with:
        configFilePath: "GitVersion.yml"
    - name: Get Version
      shell: bash
      id: get-version
      run: |
        version="${{ steps.gitversion.outputs.SemVer }}"
        echo "$version"
        echo "PACKAGE_VERSION=$version" >> $GITHUB_ENV
        ARTIFACT_NAME="${{ inputs.project-name }}-$version"
        echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV

        echo "package-version=$version" >> $GITHUB_OUTPUT
        echo "artifact-name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
    - name: Check Umbraco Version
      id: check-umbraco-version
      shell: bash
      if: ${{ inputs.strict-umbraco-version == 'true' }}
      run: |
        if [ "${{ steps.gitversion.outputs.Major }}" != "$UMBRACO_VERSION" ]; then
          echo "Umbraco version mismatch: expected $UMBRACO_VERSION but got ${{ steps.gitversion.outputs.Major }}"
          echo "Check the branch you are building from is correct, GitVersion.yml is configured correctly and that you are using the correct version of this Action for the Umbraco version you are building."
          exit 1
        fi
    - uses: actions/setup-node@v6
      if: ${{ env.NPM_ENABLED == 'true' }}
      with:
        node-version: ${{ env.NODE_VERSION }}
    - if: ${{ env.NPM_ENABLED == 'true' }}
      shell: bash
      run: |
        pushd ${{ env.NPM_WORKING_DIR }}
        npm install
        npm run ${{ env.NPM_RUN_COMMAND }}
        popd
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Build project
      shell: bash
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release -p:Version=${{ env.PACKAGE_VERSION }} --output ${{ env.ARTIFACT_OUTPUT }} --source https://api.nuget.org/v3/index.json /maxcpucount:1
    - name: Pack
      shell: bash
      if: ${{ env.DOTNET_PACK == 'true' }}
      run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release -p:Version=${{ env.PACKAGE_VERSION }} --output ${{ env.ARTIFACT_OUTPUT }}
    - name: Upload artifact
      uses: actions/upload-artifact@v5
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: "${{ env.ARTIFACT_OUTPUT }}/**/*.nupkg"
