workflow: GitHubFlow/v1
mode: ContinuousDeployment
version-in-branch-pattern: '^(?<Major>0|[1-9]\d*)$'
minor-version-bump-message: '^(semver:\s*feature|semver:\s*minor|feature:|feat:)'
branches:
  version:
    regex: ^v
    label: ""
    increment: Patch
    is-release-branch: true
    is-main-branch: true
    source-branches: ["version-develop"]
  version-develop:
    regex: ^dev/v
    mode: ContinuousDeployment
    tag: alpha
    increment: Patch
    track-merge-target: true
    is-source-branch-for: ["version"]
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: false
